from . import dotykacka_config
from . import dotykacka_oauth
from . import dotykacka_sync_log
from . import dotykacka_customer_sync
from . import dotykacka_product_sync
from . import dotykacka_order_sync
from . import dotykacka_invoice_sync
from . import dotykacka_payment_sync
from . import dotykacka_payment_method
from . import res_partner
from . import product_product
from . import sale_order
from . import account_move
from . import account_payment
